name: Feature
description: Nueva funcionalidad o mejora
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: textarea
    id: objective
    attributes:
      label: Objetivo
      description: Qué se quiere lograr y por qué
      placeholder: Describir el objetivo de la funcionalidad
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Alcance
      description: Qué incluye y qué NO incluye
      placeholder: |
        Incluye:
        - 
        No incluye:
        -
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación
      placeholder: |
        - Dado ...
        - Cuando ...
        - Entonces ...

  - type: textarea
    id: technical
    attributes:
      label: Impacto técnico
      description: Indicar impacto por área
      placeholder: |
        Backend:
        Frontend:
        Infra / Legacy:

  - type: checkboxes
    id: deploy
    attributes:
      label: Deploy manual
      options:
        - label: Requiere deploy manual en TST
